# Generated by Django 5.0.7 on 2024-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollingTextVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('video_file', models.FileField(upload_to='generate_video_path', verbose_name='Video File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Scrolling Text Video',
                'verbose_name_plural': 'Scrolling Text Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
